### ISSUE TITLE
NPC Xenos Don't Die

### ISSUE THREAD

**Issue by Lyeos** [UristMcStation/UristMcStation#752]
Making a meme report because this bug has been reported in discord about a hundred times.

#### Description of issue
Simplemob xenos do not actually die properly when you kill them, instead opting to stand upright and scream forever.

#### Difference between expected and actual behavior
They should die and not scream forever.

#### Steps to reproduce 
Kill an NPC xeno.

#### Length of time in which bug has been known to occur
Months, if not years.

**Comment by Glloyd** [comment]
Was this fixed by #713 @scrdest?

**Comment by scrdest** [comment]
Not as far as I know; IIRC I spawned a 'morph after the last update, and it was still a problem. I will need to fix SAs some more anyway, though.

**Comment by ggermanicus** [comment]
I remember this bug. Definitely fixed way long ago.
